---
- name: Mineski Prod Switch Configuration 2024 V1
  hosts: AccessSwitch1
  gather_facts: false
  tasks:
    - name: hostname
      community.routeros.command:
        commands: /system resource print
