---
- name: RouterOS test with network_cli connection
  hosts: all
  connection: network_cli
  gather_facts: false
  tasks:
   - name: Run command on remote devices
  community.routeros.command:
    commands: /system routerboard print
