---
- name: Mineski Prod Switch Configuration 2024 V1
  hosts: AccessSwitch1
  gather_facts: false
  tasks:
    - name: Run multiple commands on remote nodes
  community.routeros.command:
    commands:
      - /system routerboard print
      - /system identity print
