---
- name: Basic Mikrotik Switch Configuration
  hosts: all  # Replace with your Mikrotik group from inventory
  gather_facts: false        # Mikrotik modules don't typically use facts
  connection: network_cli    # Use network_cli for Mikrotik
  tasks:
    - name: Display System Identity
      community.routeros.command:
        commands: /system/identity/print
      register: identity_output

    - name: Display Interface List
      community.routeros.command:
        commands: /interface/print
      register: interface_output

    - name: Display IP Address List
      community.routeros.command:
        commands: /ip/address/print
      register: ip_address_output

    - name: Display Bridge List
      community.routeros.command:
        commands: /interface/bridge/print
      register: bridge_output

    - name: Display VLAN List
      community.routeros.command:
        commands: /interface/vlan/print
      register: vlan_output

    - name: Display DHCP Server List
      community.routeros.command:
        commands: /ip/dhcp-server/print
      register: dhcp_output

    - name: Display Firewall Filter Rules
      community.routeros.command:
        commands: /ip/firewall/filter/print
      register: firewall_output

    - name: Print System Identity
      debug:
        var: identity_output.stdout_lines

    - name: Print Interface List
      debug:
        var: interface_output.stdout_lines

    - name: Print IP Address List
      debug:
        var: ip_address_output.stdout_lines

    - name: Print Bridge List
      debug:
        var: bridge_output.stdout_lines

    - name: Print VLAN List
      debug:
        var: vlan_output.stdout_lines

    - name: Print DHCP Server List
      debug:
        var: dhcp_output.stdout_lines

    - name: Print Firewall Filter Rules
      debug:
        var: firewall_output.stdout_lines
    
