---
- name: Mineski Prod Switch Configuration
  hosts: StageAccessSwitch
  gather_facts: false
  tasks:
    - name: Add Bridge-Trunk
      community.routeros.command:
        commands:
          - /interface bridge add name=StageBR
